// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-usability/AccessibilityReadability.tsx": () => import("../components/mockups/landing-usability/AccessibilityReadability.tsx"),
  "./components/mockups/landing-usability/InfoHierarchy.tsx": () => import("../components/mockups/landing-usability/InfoHierarchy.tsx"),
  "./components/mockups/landing-usability/InteractionAffordance.tsx": () => import("../components/mockups/landing-usability/InteractionAffordance.tsx"),
  "./components/mockups/landing-vibes/DarkAuthoritative.tsx": () => import("../components/mockups/landing-vibes/DarkAuthoritative.tsx"),
  "./components/mockups/landing-vibes/FreshOptimistic.tsx": () => import("../components/mockups/landing-vibes/FreshOptimistic.tsx"),
  "./components/mockups/landing-vibes/WarmHuman.tsx": () => import("../components/mockups/landing-vibes/WarmHuman.tsx")
};
